export const currencyByRupee: Currency[] = [
  {
    name: "RUPEE",
    value: 1,
    flag: "🇮🇳",
    symbol: "₹",
  },
  {
    name: "DOLLAR",
    value: 0.012271428,
    flag: "🇺🇸",
    symbol: "$",
  },
  {
    name: "EURO",
    value: 0.01125809,
    flag: "🇪🇺",
    symbol: "€",
  },
  {
    name: "POUND",
    value: 0.0099194378,
    flag: "🇬🇧",
    symbol: "£",
  },
  {
    name: "RUBEL",
    value: 0.85040469,
    flag: "🇷🇺",
    symbol: "₽",
  },
  {
    name: "AUS DOLLAR",
    value: 0.01732574,
    flag: "🇦🇺",
    symbol: "A$",
  },
  {
    name: "CAN DOLLAR",
    value: 0.016457908,
    flag: "🇨🇦",
    symbol: "C$",
  },
  {
    name: "YEN",
    value: 1.5909089,
    flag: "🇯🇵",
    symbol: "¥",
  },
  {
    name: "DINAR",
    value: 0.0037446993,
    flag: "🇰🇼",
    symbol: "KD",
  },
  {
    name: "BITCOIN",
    value: 0.000000543544886,
    flag: "🎰",
    symbol: "₿",
  },
  {
    name: "SWISS FRANC",
    value: 0.011214,
    flag: "🇨🇭",
    symbol: "CHF",
  },
  {
    name: "CHINESE YUAN",
    value: 0.088304,
    flag: "🇨🇳",
    symbol: "¥",
  },
  {
    name: "UAE DIRHAM",
    value: 0.045064,
    flag: "🇦🇪",
    symbol: "د.إ",
  },
  {
    name: "SINGAPORE DOLLAR",
    value: 0.016214,
    flag: "🇸🇬",
    symbol: "S$",
  },
  {
    name: "SOUTH KOREAN WON",
    value: 15.45123,
    flag: "🇰🇷",
    symbol: "₩",
  },
  {
    name: "BRAZILIAN REAL",
    value: 0.059214,
    flag: "🇧🇷",
    symbol: "R$",
  },
  {
    name: "SAUDI RIYAL",
    value: 0.046046,
    flag: "🇸🇦",
    symbol: "﷼",
  },
  {
    name: "SOUTH AFRICAN RAND",
    value: 0.222741,
    flag: "🇿🇦",
    symbol: "R",
  },
  {
    name: "TURKISH LIRA",
    value: 0.332941,
    flag: "🇹🇷",
    symbol: "₺",
  },
  {
    name: "MALAYSIAN RINGGIT", 
    value: 0.051214,
    flag: "🇲🇾",
    symbol: "RM",
  },
  {
    name: "chineese YUAN",
    value: 0.088304,
    flag: "🇨🇳",
    symbol: "¥",
  },
  {
    name: "pakistani RUPEE",
    value: 2.0,
    flag: "🇵🇰",
    symbol: "₨",
  },
];
